-- Step 1: Staging Schema
CREATE SCHEMA IF NOT EXISTS staging;

CREATE TABLE staging.geds_raw (
    Surname text,
    GivenName text,
    Initials text,
    "Prefix (EN)" text,
    "Prefix (FR)" text,
    "Suffix (EN)" text,
    "Suffix (FR)" text,
    "Title (EN)" text,
    "Title (FR)" text,
    "Telephone Number" text,
    "Fax Number" text,
    "TDD Number" text,
    "Secure Telephone Number" text,
    "Secure Fax Number" text,
    "Alternate Telephone Number" text,
    Email text,
    "Street Address (EN)" text,
    "Street Address (FR)" text,
    "Country (EN)" text,
    "Country (FR)" text,
    "Province (EN)" text,
    "Province (FR)" text,
    "City (EN)" text,
    "City (FR)" text,
    "Postal Code" text,
    "PO Box (EN)" text,
    "PO Box (FR)" text,
    Mailstop text,
    "Building (EN)" text,
    "Building (FR)" text,
    Floor text,
    Room text,
    "Administrative Assistant" text,
    "Administrative Assistant Telephone Number" text,
    "Executive Assistant" text,
    "Executive Assistant Telephone Number" text,
    "Department Acronym" text,
    "Department Name (EN)" text,
    "Department Name (FR)" text,
    "Organization Acronym" text,
    "Organization Name (EN)" text,
    "Organization Name (FR)" text,
    "Organization Structure (EN)" text,
    "Organization Structure (FR)" text
);
